apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-event-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-event-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-event-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-event-api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  azure:
    application:
      enabled: true
  ingresses:
    - "https://tms-event-api.ekstern.dev.nav.no/tms-event-api"
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 64Mi
